version: "3"
services:
  db:
    image: mysql:latest
    container_name: jklee_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'jklee_test'
      MYSQL_USER: 'jklee_test'
      MYSQL_PASSWORD: 'jklee_password'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - /Users/jklee/datadir:/var/lib/mysql

  boot:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

